apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: calendario-ci-cd
spec:
  tasks:
    - name: install
      taskSpec:
        steps:
          - name: npm-install
            image: node:20
            script: |
              #!/bin/sh
              npm install
    - name: test
      runAfter: ["install"]
      taskSpec:
        steps:
          - name: npm-test
            image: node:20
            script: |
              #!/bin/sh
              npm run test
    - name: build
      runAfter: ["test"]
      taskSpec:
        steps:
          - name: npm-build
            image: node:20
            script: |
              #!/bin/sh
              npm run build
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc start-build progetto-calendario --from-dir=dist --wait
