apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: calendario-ci-cd
spec:
  pipelineRef:
    name: calendario-ci-cd
  workspaces:
    - name: shared-workspace
      git:
        url: https://github.com/guitarray/progetto-calendario.git
  tasks:
    - name: install
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-install
            image: node:20
            workingDir: $(workspaces.source.path)
            script: |
            #!/bin/sh
            cd $(workspaces.source.path)
            npm install
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: test
      runAfter: ["install"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-test
            image: node:20
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              npm run test
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      runAfter: ["test"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-build
            image: node:20
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              npm run build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      runAfter: ["build"]
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc start-build progetto-calendario --from-dir=$(workspaces.source.path)/dist --wait
      workspaces:
        - name: source
          workspace: shared-workspace
