apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: calendario-ci-cd
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskSpec:
        workspaces:
          - name: output
        steps:
          - name: git-clone
            image: alpine/git
            script: |
              #!/bin/sh
              echo "Cloning repository..."
              git clone https://github.com/guitarray/progetto-calendario.git $(workspaces.output.path)
              ls -l $(workspaces.output.path)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: install
      runAfter: ["clone"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-install
            image: node:20
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              echo "Running npm install in $(workspaces.source.path)"
              ls -l
              npm install
      workspaces:
        - name: source
          workspace: shared-workspace
