apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: calendario-ci-cd
spec:
  workspaces:
    - name: source
  tasks:
    - name: install
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: clone-and-npm-install
            image: node:20
            script: |
              #!/bin/sh
              git clone https://github.com/guitarray/progetto-calendario.git $(workspaces.source.path)
              cd $(workspaces.source.path)
              npm install

    - name: test
      runAfter: ["install"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-test
            image: node:20
            script: |
              #!/bin/sh
              cd $(workspaces.source.path)
              npm run test

    - name: build
      runAfter: ["test"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-build
            image: node:20
            script: |
              #!/bin/sh
              cd $(workspaces.source.path)
              npm run build

    - name: deploy
      runAfter: ["build"]
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc start-build progetto-calendario --from-dir=$(workspaces.source.path)/dist --wait
      workspaces:
        - name: source
          workspace: source
