apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: calendario-ci-cd-run
spec:
  pipelineRef:
    name: calendario-ci-cd
  workspaces:
    - name: shared-workspace
      emptyDir: {}
  params: []
