apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: calendario-ci-cd
spec:
  workspaces:
    - name: source
  tasks:
    - name: install
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-install
            image: node:20
            script: |
              #!/bin/sh
              mkdir -p $(workspaces.source.path)/app
              git clone https://github.com/guitarray/progetto-calendario.git $(workspaces.source.path)/app
              cd $(workspaces.source.path)/app
              npm install

    - name: test
  runAfter: ["install"]
  taskSpec:
    workspaces:
      - name: source
    steps:
      - name: npm-test
        image: node:20
        workingDir: $(workspaces.source.path)
        script: |
          #!/bin/sh
          npm run test
  workspaces:
    - name: source
      workspace: source

    - name: build
      runAfter: ["test"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: npm-build
            image: node:20
            script: |
              #!/bin/sh
              cd $(workspaces.source.path)/app
              npm run build

    - name: deploy
      runAfter: ["build"]
      taskRef:
        apiVersion: tekton.dev/v1beta1
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc start-build progetto-calendario --from-dir=$(workspaces.source.path)/app/dist --wait
      workspaces:
        - name: source
          workspace: source
